[package]
org = "dushan"
name = "dataintegration"
version = "0.1.0"

[build-options]
observabilityIncluded = true
remoteManagement=true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

